[phases.setup]
nixPkgs = ['nodejs_20', 'python3']

[phases.install]
cmds = ['npm install --omit=dev --production']

[phases.build]
cmds = ['echo "No build step required"']

[start]
cmd = 'node backend/server.js'
